### ISSUE TITLE
Not reconnected after 502 error

### ISSUE THREAD

**Issue by Chiliec** [Otann/morse#26]
We using `morse.pooling`. After telegram returning 502 error:
```html
Oct 29, 2017 9:36:29 PM morse.api invoke
SEVERE: Telegram returned 502 from /getUpdates: <html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.10.0</center>
</body>
</html>
```
bot stops receiving requests. But expected behavior is trying to reconnect.

**Comment by jonathanj** [comment]
I'm also experiencing this issue. I don't think the consumer loop exits and so no more updates are ever fetched.

The issue appears to be in the use of `alts!` in `create-producer`: `(api/get-updates)` returns `nil` (via `log/error`) when an error status code is returned, which means `data` (via `alts!`) is `nil` and thus the updates channel is closed and the `create-consumer` loop exits.

I think the consumer code needs to check the channel value returned from `alts!` instead of throwing it away, if the channel is the `running` channel then indeed it's time to exit. If it's the `resopnse` channel then the loop should recur at the current offset.

**Comment by Otann** [comment]
@Chiliec Here, I fixed it. ;)
Released `0.2.8` to clojars

**Comment by Otann** [comment]
@jonathanj you were right, changed nil to `::error`

**Comment by jonathanj** [comment]
There's another case, in the same code:

```
SEVERE: Telegram returned 502 from /getUpdates: <html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.10.1</center>
</body>
</html>
```

This results in `::error` being returned from `api/get-updates` which the producer code tries to loop over with `(doseq [upd data] ...)`, probably resulting in the loop not recurring.

**Comment by jonathanj** [comment]
Sorry, I was reading a mixed portion of old and new code. Thank you @Otann.
